spring.application.name=spring-ai-docker

spring.ai.openai.api-key=dummy
spring.ai.openai.chat.base-url=http://localhost:12434/engines/v1
spring.ai.openai.chat.model=ai/gemma4

spring.ai.model.embedding=transformers

spring.ai.openai.embedding.base-url=http://localhost:12434/engines/v1
spring.ai.openai.embedding.model=gemma4

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=rag